### ISSUE TITLE
expiration of Qr code and link

### ISSUE THREAD

**Issue by Jmomanyi** [Intina47/app1#15]
Extract the countdown and  verify and both qr code and link should expire

**Comment by Intina47** [comment]
i think we just need a time stamp on the database for when the uuid has been activated and then 24 hours later we deactivate it in someway.
I was thinking we can delete the uuid after 24 hours of activation but that means if the user registers again the uuid will be created for them again.

**Comment by Intina47** [comment]
> Extract the countdown and  verify and both qr code and link should expire

Actually even much better and easier, we can still use the Local storage, if the countdown goes to 00:00:00:00 then we e display a message, qr code expired
